### ISSUE TITLE
Assembly conflict 

### ISSUE THREAD

**Issue by scharada** [VahidN/MvcPlugin#2]
hello, thank you for sharing the project.

the solution does not compile with the following errors in several projects of the solution:

Severity    Code    Description Project File    Line    Suppression State
Error   CS0012  The type 'ValidationAttribute' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.   CommonEntities  ....\MvcPlugin-master\Plugins\CommonEntities\CommonEntities\User.cs 11  Active

when you do reference the requested assembly, another conflict appears:
Severity    Code    Description Project File    Line    Suppression State
Error   CS0433  The type 'MaxLengthAttribute' exists in both 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' and 'System.ComponentModel.DataAnnotations, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'    CommonEntities  .....\MvcPlugin-master\Plugins\CommonEntities\CommonEntities\User.cs    11  Active

can you please suggest a fix ? i suppose the attributes having the conflict are required by design

**Comment by scharada** [comment]
forgott to mention that the errors happen after upgrading to .Net 4.5 and up.

**Comment by VahidN** [comment]
If you issue the following NuGet command, it will remove the old and conflicting EF assemblies
`PM> update-package`
Also if you have changed the target framework, you need to issue this command as well
`PM> update-package -Reinstall`

**Comment by VahidN** [comment]
I've updated the solution to .NET 4.5 and ASP.NET MVC 5.x.

**Comment by scharada** [comment]
great thank you.
i'll give it a shot.

**Comment by scharada** [comment]
Hi Wahid, it works fine , thank you.

I’d like to add Install/Uninstall + dynamic loading and unloading  of plugins. Where do you think it can be added in your code ? 

Thank you for your advice.

Souheil.

**Comment by VahidN** [comment]
It loads the plugins dynamically. The main project has no reference to any of the plugins.
[More info in Persian](http://www.dotnettips.info/post/2067/%d8%b7%d8%b1%d8%a7%d8%ad%db%8c-%d8%a7%d9%81%d8%b2%d9%88%d9%86%d9%87-%d9%be%d8%b0%db%8c%d8%b1-%d8%a8%d8%a7-asp-net-mvc-4-x-5-x-%d9%82%d8%b3%d9%85%d8%aa-%d8%a7%d9%88%d9%84)

**Comment by scharada** [comment]
Hi,

I realize that. What I would like to do is not load automatically but :
- ```
       Recognize and validate the plugins
  ```
- ```
       Display in a list
  ```
- ```
       Be able to invoke install/uninstall a plugin  (install source could be a nugget package or zip)
  ```
- ```
       Be able to activate/deactivate a plugin (installed but not active).
  ```

I was hoping to have your advice on how to accomplish this.

There are other points of interest :
- ```
       Main App < == > Plugin communication/notification and data exchange
  ```
- ```
       Plugin < == > Plugin communication/notification and data exchange.
  ```

Knowing that plugins are assemblies that are independent from the main app and other plugins, what would be the best way to achieve that. Would a Pub/Sub events notification mechanism be the right approach and how to limit it to the current user context (not application context) or both.

Souheil.

**Comment by VahidN** [comment]
- Unloading plugins in web app's is not as easy as desktop apps. In .NET framework, you cannot eject/unload a loaded assembly without unloading the whole App Domain and unloading the App domain in Web Apps means restart (losing all the sessions, etc.). It's possible to create a separate app domain too (having multiple app domains), but in Web Apps you will lose the communication with the main app and everything related to it, because app domains are isolated from each other.
  So when a plugin is loaded in the current app domain, it will be there until the next restart of the app domain. This is how the .NET manages assemblies.
- Restarting the app domain of a web application is as easy as dropping a new .dll file in the .bin folder (any changes in the .bin folder will restart the app domain).
